trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

jobs:

#
# Windows
#

# TODO:

#
# Linux
#

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    framework: 'netcoreapp3.0'
    solution: 'password-manager-access.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - bash: 'compgen -c | sort'
    displayName: 'compgen'

  - bash: 'env'
    displayName: 'env'

  - bash: 'echo yo > test.txt'
    displayName: 'make test file'

  - bash: 'pwd; ls -lR'
    displayName: 'list files'

  - publish: .
    artifact: package

#
# Release to GitHub
#

- job: Release

  dependsOn:
  #- Windows
  - Linux

  #condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - download: current
    artifact: package

  - bash: 'pwd; ls -lR'
    displayName: 'pwd, ls'

  - bash: 'ls -lR $(Pipeline.Workspace)'
    displayName: 'ls Workspace'

  - bash: 'env'
    displayName: 'env'

  - bash: 'compgen -c | sort'
    displayName: 'compgen'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github-release
      assets: $(Pipeline.Workspace)/**/*.txt
      tagSource: manual
      tag: $(Build.SourceBranchName)
